name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 8, 11 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.jdk}}
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f .travis-requirements.txt ]; then pip install -r .travis-requirements.txt; fi
      - name: Github Environment Setup
        run: echo "DUMMY_VAR=dummy" >> $GITHUB_ENV
      - name: Security Demo Setup & Build
        run: ./setup.sh
      - name: Security Demo Tests
        run: ./test-security.sh

